openapi: 3.0.1
info:
  title: MilkBot lactation API
  description: >-
    This service uses the MilkBot&reg; fitting engine to fit the MilkBot&reg;
    model to lactation data supplied as (DIM, milk weight) data points.  The
    returned parameter set can be substituted into the MilkBot&reg;
    equation<br><br> ((1 - E^((offset - t)/ramp)/2)*scale)/E^(decay X t)
    <br><br>to generate predicted milk production at any time in the lactation,
    where t is time since calving (in days, DIM=0 at calving) and E is Euler's
    number.<br><br> Simple formulas described at the support URL can calculate
    persistence, M305, or cumulative milk between dates. The fitting process
    uses Bayesian priors describing expected means and variance of parameter
    values as well as expected mean and variance in fitting error. If priors are
    provided, they will be used. Otherwise default values based on breed and
    parity will be used
  termsOfService: http://MilkBot.com/terms/
  contact:
    name: Jim Ehrlich, DVM
    email: jehrlich@MilkBot.com
  version: 1.2.0
servers:
  - description: Production server
    url: >-
      https://europe-west1-numeric-analogy-337601.cloudfunctions.net/milkBot-fitter
security:
  - ApiKeyAuth: []
paths:
  /fitLactation:
    $ref: paths/fitLactation.yaml
  /fitLactations:
    $ref: paths/fitLactations.yaml
  /Priors/{milkUnit}:
    $ref: paths/Priors@{milkUnit}.yaml
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
