required:
  - decay
  - id_key
  - ramp
  - scale
type: object
properties:
  id_key:
    type: string
    description: >-
      an identifier to key fitted parameters to a lactation  with the same
      id_key in the request. For this reason, id_key values should be unique
      within a LactationList.
  scale:
    type: number
    description: >-
      Overall scale of milk production in units specified by milk_unit. The
      MilkBot&reg; model can be converted to another unit of measurement for
      milk simply by multiplying the scale parameter by an appropriate
      conversion factor
    format: float
  ramp:
    type: number
    description: Length of ramp-up period at start of lactation, in days.
    format: float
  offset:
    type: number
    description: Offset between calving and theoretical start of lactation in days.
    format: float
    default: 0
  decay:
    type: number
    description: >-
      first order decay constant in inverse-days that controls the decline in
      milk production.
    format: float
  milk_unit:
    $ref: ./MilkUnit.yaml
description: Parameter set for the MilkBot&reg; model
