openapi: 3.0.1
info:
  title: MilkBot lactation API
  description: This service uses the MilkBot&reg; fitting engine to fit the MilkBot&reg;
    model to lactation data supplied as (DIM, milk weight) data points.  The returned
    parameter set can be substituted into the MilkBot&reg; equation<br><br> ((1 -
    E^((offset - t)/ramp)/2)*scale)/E^(decay X t) <br><br>to generate predicted milk
    production at any time in the lactation, where t is time since calving (in days,
    DIM=0 at calving) and E is Euler's number.<br><br> Simple formulas described at
    the support URL can calculate persistence, M305, or cumulative milk between dates.
    The fitting process uses Bayesian priors describing expected means and variance
    of parameter values as well as expected mean and variance in fitting error. If
    priors are provided, they will be used. Otherwise default values based on breed
    and parity will be used
  termsOfService: http://MilkBot.com/terms/
  contact:
    name: Jim Ehrlich, DVM
    email: jehrlich@MilkBot.com
  version: 1.2.0
servers:

security:
  - internalApiKey: []
paths:
  /fitLactation:
    get:
      summary: Fit a lactation.
      description: This endpoint fits a single lactation from the supplied (DIM, milk
        weight) data pairs using a default set of Bayesian priors based on breed and
        parity
      requestBody:
        description: a single lactation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lactation'
          application/xml:
            schema:
              $ref: '#/components/schemas/Lactation'
        required: true
      responses:
        200:
          description: Lactation fitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MBParams'
            application/xml:
              schema:
                $ref: '#/components/schemas/MBParams'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - internalApiKey: []
      x-codegen-request-body-name: lactation
  /fitLactations:
    post:
      summary: Fit a list of lactations.
      description: This endpoint fits a group of lactations using  customized priors
        if they are supplied, or a default set of  priors based on breed and parity.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LactationList'
          application/xml:
            schema:
              $ref: '#/components/schemas/LactationList'
        required: true
      responses:
        200:
          description: MBParams List for fitted lactations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MBParamsList'
            application/xml:
              schema:
                $ref: '#/components/schemas/MBParamsList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - internalApiKey: []
      x-codegen-request-body-name: lactations
components:
  schemas:
    MBParams:
      required:
        - decay
        - id_key
        - ramp
        - scale
      type: object
      properties:
        id_key:
          type: string
          description: an identifier to key fitted parameters to a lactation  with
            the same id_key in the request. For this reason, id_key values should
            be unique within a LactationList.
        scale:
          type: number
          description: Overall scale of milk production in units specified by milk_unit.
            The MilkBot&reg; model can be converted to another unit of measurement
            for milk simply by multiplying the scale parameter by an appropriate conversion
            factor
          format: float
        ramp:
          type: number
          description: Length of ramp-up period at start of lactation, in days.
          format: float
        offset:
          type: number
          description: Offset between calving and theoretical start of lactation in
            days.
          format: float
          default: 0.0
        decay:
          type: number
          description: first order decay constant in inverse-days that controls the
            decline in milk production.
          format: float
        pt_ct:
          type: number
          description: number of data points used to calculate fitted parameters.
          format: integer
        std_error:
          type: number
          description: standard deviation of residuals between data points and fitted
            curve.
          format: float
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
      description: Parameter set for the MilkBot&reg; model
    MilkUnit:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          description: abbreviated name of measurement unit lb=pounds, kg=kilograms,
            l=liters, g=grams
          default: kg
          enum:
            - lb
            - kg
            - l
            - g
      description: Unit of measurement used for scale and milk weights, defaulting
        to kg.
    Lactation:
      required:
        - id_key
        - points
      type: object
      properties:
        id_key:
          type: string
          description: an identifier to key this lactation to a MBParams object with
            the same id_key in the response. For this reason, id_key values should
            be unique within a LactationList.
        breed:
          type: string
          description: breed of cow
          default: H
          enum:
            - H
            - J
            - BS
            - G
            - X
        parity:
          type: number
          description: parity of this lactation
          format: integer
        points:
          type: array
          items:
            $ref: '#/components/schemas/MilkPt'
        unit:
          $ref: '#/components/schemas/MilkUnit'
      description: A single lactation of any length.
    MilkPt:
      required:
        - dim
        - milk
      type: object
      properties:
        dim:
          type: number
          description: Days since calving date
          format: integer
        milk:
          type: number
          description: quantity of milk produced in one day, or a fraction of a day
            if day_fraction is supplied. Milk is measured in units specified by milk_unit,
            defaulting to kg.
          format: float
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
        day_fraction:
          type: number
          description: fraction of one day's production that milk value represents,
            defaulting to 1.0
          format: float
          default: 1.0
      description: Measured milk production data point.
    LactationList:
      required:
        - lactations
      type: object
      properties:
        name:
          type: string
          description: name for this group of lactations
        lactations:
          type: array
          items:
            $ref: '#/components/schemas/Lactation'
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
        priors:
          $ref: '#/components/schemas/PopulationPriors'
      description: A list of lactations.
    MBParamsList:
      required:
        - mbparams
      type: object
      properties:
        name:
          type: string
          description: name for this group of lactations
        mbparams:
          type: array
          items:
            $ref: '#/components/schemas/MBParams'
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
      description: A list of MBParams.
    PopulationPriors:
      type: object
      properties:
        means:
          $ref: '#/components/schemas/MBParams'
        variance:
          $ref: '#/components/schemas/MBParams'
      description: Optional Bayesian prior expectations for use by fitting engine.
        If not provided, defaults based on breed and parity will be used.
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string
  securitySchemes:
    internalApiKey:
      type: apiKey
      name: api_key
      in: header
