openapi: 3.0.1
info:
  title: MilkBot lactation API
  description: >-
    This service uses the MilkBot&reg; fitting engine to fit the MilkBot&reg;
    model to lactation data supplied as (DIM, milk weight) data points.  The
    returned parameter set can be substituted into the MilkBot&reg;
    equation<br><br> ((1 - E^((offset - t)/ramp)/2)*scale)/E^(decay X t)
    <br><br>to generate predicted milk production at any time in the lactation,
    where t is time since calving (in days, DIM=0 at calving) and E is Euler's
    number.<br><br> Simple formulas described at the support URL can calculate
    persistence, M305, or cumulative milk between dates. The fitting process
    uses Bayesian priors describing expected means and variance of parameter
    values as well as expected mean and variance in fitting error. If priors are
    provided, they will be used. Otherwise default values based on breed and
    parity will be used
  termsOfService: http://MilkBot.com/terms/
  contact:
    name: Jim Ehrlich, DVM
    email: jehrlich@MilkBot.com
  version: 1.2.0
paths:
  /fitLactation:
    get:
      operationId: fitSingle
      description: >-
        Fit a single lactation from the supplied (DIM, milk weight) data pairs
        using a default set of Bayesian priors based on breed and parity
      requestBody:
        description: a single lactation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lactation'
        required: true
      responses:
        '200':
          description: Lactation fitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Params'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /fitLactations:
    post:
      summary: Fit a list of lactations.
      description: >-
        This endpoint fits a group of lactations using  customized priors if
        they are supplied, or a default set of  priors based on breed and
        parity.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LactationSet'
        required: true
      responses:
        '200':
          description: MBParams List for fitted lactations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PopulationPriors'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    internalApiKey:
      type: apiKey
      name: api_key
      in: header
  schemas:
    MilkUnit:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          description: >-
            abbreviated name of measurement unit lb=pounds, kg=kilograms,
            l=liters, g=grams
          default: kg
          example: kg
          enum:
            - lb
            - kg
            - l
            - g
      description: Unit of measurement used for scale and milk weights, defaulting to kg.
    MilkPt:
      required:
        - dim
        - milk
      type: object
      properties:
        dim:
          type: number
          format: integer
          description: Days since calving date
          example: 33
        milk:
          type: number
          format: float
          example: 21
          description: >-
            quantity of milk produced in one day, or a fraction of a day if
            day_fraction is supplied. Milk is measured in units specified by
            milk_unit, defaulting to kg.
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
        day_fraction:
          type: number
          format: float
          default: 1
          example: 0.5
          description: >-
            fraction of one day's production that **_milk_** represents,
            defaulting to 1.0
      description: Measured milk production data point.
    Lactation:
      required:
        - id_key
        - points
      type: object
      properties:
        id_key:
          type: string
          example: Bossie123
          description: >-
            an identifier to key this lactation to a MBParams object with the
            same id_key in the response. For this reason, id_key values should
            be unique within a LactationList.
        breed:
          type: string
          description: breed of cow
          default: H
          example: J
        parity:
          type: number
          description: parity of this lactation
          format: integer
          example: 1
        points:
          type: array
          items:
            $ref: '#/components/schemas/MilkPt'
        unit:
          $ref: '#/components/schemas/MilkUnit'
      description: A single lactation of any length.
    Error:
      type: object
      description: error response per RFC 7807
      required:
        - title
        - status
      properties:
        errorType:
          type: string
          description: a URI identifier that categorizes the error
          example: /errors/incorrect-user-pass
        title:
          type: string
          description: A brief, human-readable message about the error
          example: incorrect username or password
        status:
          type: integer
          description: HTTP status code
          example: 400
        detail:
          type: string
          description: a human-readable description of the specific error
          example: Authentication failed due to incorrect username or password.
        instance:
          type: string
          description: a URI that identifies the specific occurrence of the error
          example: /login/log/abc123
    Params:
      required:
        - decay
        - id_key
        - ramp
        - scale
      type: object
      properties:
        id_key:
          type: string
          example: Bossie12345
          description: >-
            an identifier to key fitted parameters to a lactation  with the same
            id_key in the request. For this reason, id_key values should be
            unique within a LactationList.
        scale:
          type: number
          example: 45.5
          description: >-
            Overall scale of milk production in units specified by milk_unit.
            The MilkBot&reg; model can be converted to another unit of
            measurement for milk simply by multiplying the scale parameter by an
            appropriate conversion factor
          format: float
        ramp:
          type: number
          example: 20
          description: Length of ramp-up period at start of lactation, in **days**.
          format: float
        offset:
          type: number
          description: Offset between calving and theoretical start of lactation in days.
          format: float
          example: 0
          default: 0
        decay:
          type: number
          description: >-
            first order decay constant in inverse-days that controls the decline
            in milk production.
          format: float
          example: 0.02
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
      description: Parameter set for the MilkBot&reg; model
    PopulationPriors:
      type: object
      properties:
        means:
          $ref: '#/components/schemas/Params'
        sd:
          $ref: '#/components/schemas/Params'
        seMilk:
          type: number
          format: float
          description: standard error in measurement of milk per day
          example: 5.2
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
      description: >-
        Optional Bayesian prior expectations for use by fitting engine. If not
        provided, defaults based on breed and parity will be used. **_means_**
        are expected mean parameter values for the population **_sd_** are
        expected standard deviation of parameter values for the population
        **_seMilk_** is expected standard error of milk measurements excluding
        the effects of a normal lactation curve
    LactationSet:
      required:
        - lactations
      type: object
      properties:
        name:
          type: string
          description: name for this group of lactations
          example: Example Farm
        lactations:
          type: array
          items:
            $ref: '#/components/schemas/Lactation'
        milk_unit:
          $ref: '#/components/schemas/MilkUnit'
        priors:
          type: array
          items:
            $ref: '#/components/schemas/PopulationPriors'
      description: A list of lactations.
