name: Manual Lint

on:
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Redoc Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: openapi-lint 
        uses: mhiew/redoc-lint-github-action@v2
        with:
          args: 'src/openapi.yaml'
