name: split OAS

on:
  workflow_dispatch: #manual trigger or ...
  push: #when changes are pushed to default branch for the file src/openAPI.yml
    branches:
      - master
    paths:
      - "src/openAPI.yml"
jobs:

  split:
    runs-on: ubuntu-latest
    name: OAS Splitter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CLI split
        run: npx @redocly/openapi-cli split src/openapi.yaml --outDir='src/split'
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'split src/openapi.yaml to src/split'
          add: 'src/split/*.yaml'